package net.alexheavens.cs4099.simulation;

public enum SimEventType {
	NODE_PAUSE, NODE_UNPAUSE, MESSAGE_ARRIVAL, MESSAGE_SENT, MESSAGE_READ, NODE_FAILURE, NODE_RECEIVE_BLOCK, NODE_RECEIVE_UNBLOCK, COLOUR_CHANGE_EVENT, NODE_REMOTE_KILL
}
